### ISSUE TITLE
Licence request

### ISSUE THREAD

**Issue by jaustin** [r59q/mkcd-ml-machine#1]
Hi @r59q - I was looking at deriving an extension from this that is a more generic 'ble commands' system - there are a bunch of useful bits here I'd like to use but as there's no licence didn't want to drag them in.

FWIW, we require MIT licence for approving MakeCode extensions as part of the core list, so that would be an ideal choice!  (see https://makecode.microbit.org/extensions/approval for context, but it's because once we approve an extension, we want to be sure we are able to update/fix/evolve it so our users can keep using it even if the original author walks away :) )

**Comment by r59q** [comment]
You are of course more than welcome to base something on this repository, thank you for bringing it to my attention 👍
